### ISSUE TITLE
Typo in the name of folder Artificial Intelligence

### ISSUE THREAD

**Issue by shreyaansjain06** [Alphasians/Learning-Resources#1]
**Description**

**Stack**

Project stack or language (eg. Frontend):

**Working Environment**

Operating System (eg Linux):

Browser (eg. Chrome):

Device (eg. Laptop or Phone):

**Screenshots**

[Optional] **Additional Context**

**Comment by Sonichigo** [comment]
Thanks for this👍!
https://github.com/Alphasians/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization Join the github org and discord there we will be discussion about the hacktoberfest and all!
